# Generated by Django 3.2.4 on 2022-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'Строка в таблице',
                'verbose_name_plural': 'Строки в таблице',
            },
        ),
    ]
